# Generated by Django 3.2 on 2025-10-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='createTime',
            field=models.DateField(auto_now_add=True, verbose_name='注册时间'),
        ),
    ]
