# Generated by Django 3.2 on 2025-10-13 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_commentdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户数据',
                'db_table': 'user',
            },
        ),
    ]
